version: "3.8"

services:
  ingestionrag:
    container_name: ingestionrag1
    build: .
    image: ingestionrag1:latest
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./artifacts:/app/artifacts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s